from __future__ import annotations

from enum import StrEnum


class PrivacyLevel(StrEnum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
    LOCAL_ONLY = "LOCAL_ONLY"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ProjectStatus(StrEnum):
    CREATED = "CREATED"
    RESEARCHING = "RESEARCHING"
    PLANNING = "PLANNING"
    READY = "READY"
    IMPLEMENTING = "IMPLEMENTING"
    TESTING = "TESTING"
    REVIEWING = "REVIEWING"
    STAGING = "STAGING"
    VERIFYING_STAGING = "VERIFYING_STAGING"
    DEPLOYING = "DEPLOYING"
    VERIFYING_PRODUCTION = "VERIFYING_PRODUCTION"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    PAUSED = "PAUSED"


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_DEPENDENCY = "WAITING_DEPENDENCY"
    WAITING_PROVIDER = "WAITING_PROVIDER"
    TESTING = "TESTING"
    REVIEWING = "REVIEWING"
    FIX_REQUIRED = "FIX_REQUIRED"
    APPROVED = "APPROVED"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"
